### ISSUE TITLE
another billy creation no one asked for but needed

### ISSUE THREAD

**Issue by NoSharp** [WilliamVenner/gm_cpreprocessor#1]
another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed another billy creation no one asked for but needed

**Comment by WilliamVenner** [comment]
i hope someone makes a workshop addon that depends on this

**Comment by NoSharp** [comment]
I will

**Comment by WilliamVenner** [comment]
issue resolved!
